### ISSUE TITLE
Issue fetching favicon from EBay

### ISSUE THREAD

**Issue by WatsonBerlin** [ComputerGhost/FaviconFetcher#4]
There seems to be an issue with the EBay favicon at https://www.ebay.de/. 
The function fetcher.Fetch fails with an exception.
The function scanner.Scan works however, but shows these results (the first one is broken):

https://pages.ebay.com/favicon.ico><meta
https://www.ebay.de/favicon.ico

Perhaps you can fix it, so I can use the first function.
Another issue is that the plugin hangs forever if it takes too long to fetch an icon or no icon is found. I have added a cancellation token, which cancels the function after 2 seconds, which works fine.

**Comment by ComputerGhost** [comment]
Ebay problem fixed in latest version 1.3.0.  I made a separate ticket for the cancellation token, which wasn't added in this version.
